# Generated by Django 5.0.6 on 2024-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0004_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtituloE3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtituloE3', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='subtituloE3',
        ),
    ]
